/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class Anw_Seq1 extends Anw_Seq {

  public Anw anw;

  public Anw_Seq1 (Anw anw) {
    this.anw = anw;
    if (anw != null) anw.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (anw != null) anw.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (anw != null) anw.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (anw != null) anw.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Anw_Seq1(\n");
      if (anw != null)
        buffer.append(anw.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Anw_Seq1]");
    return buffer.toString();
  }
}
