/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class Array_Variable extends Var_Dekl {

  public int laenge;
  public Typ typ;
  public Id_Seq id_Seq;

  public Array_Variable (int laenge, Typ typ, Id_Seq id_Seq) {
    this.laenge = laenge;
    this.typ = typ;
    if (typ != null) typ.setParent(this);
    this.id_Seq = id_Seq;
    if (id_Seq != null) id_Seq.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (typ != null) typ.accept(visitor);
    if (id_Seq != null) id_Seq.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (typ != null) typ.traverseTopDown(visitor);
    if (id_Seq != null) id_Seq.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (typ != null) typ.traverseBottomUp(visitor);
    if (id_Seq != null) id_Seq.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Array_Variable(\n");
    buffer.append("  "+tab+laenge);
    buffer.append("\n");
      if (typ != null)
        buffer.append(typ.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (id_Seq != null)
        buffer.append(id_Seq.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Array_Variable]");
    return buffer.toString();
  }
}
