/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class ArrayAusdr extends Var {

  public String ident;
  public Ausdr index;

  public ArrayAusdr (String ident, Ausdr index) {
    this.ident = ident;
    this.index = index;
    if (index != null) index.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (index != null) index.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (index != null) index.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (index != null) index.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ArrayAusdr(\n");
    buffer.append("  "+tab+ident);
    buffer.append("\n");
      if (index != null)
        buffer.append(index.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ArrayAusdr]");
    return buffer.toString();
  }
}
