/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class BinAusdr extends Ausdr {

  public Ausdr ausdr;
  public int op;
  public Ausdr ausdr2;

  public BinAusdr (Ausdr ausdr, int op, Ausdr ausdr2) {
    this.ausdr = ausdr;
    if (ausdr != null) ausdr.setParent(this);
    this.op = op;
    this.ausdr2 = ausdr2;
    if (ausdr2 != null) ausdr2.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (ausdr != null) ausdr.accept(visitor);
    if (ausdr2 != null) ausdr2.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (ausdr != null) ausdr.traverseTopDown(visitor);
    if (ausdr2 != null) ausdr2.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (ausdr != null) ausdr.traverseBottomUp(visitor);
    if (ausdr2 != null) ausdr2.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("BinAusdr(\n");
      if (ausdr != null)
        buffer.append(ausdr.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+op);
    buffer.append("\n");
      if (ausdr2 != null)
        buffer.append(ausdr2.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [BinAusdr]");
    return buffer.toString();
  }
}
