/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ClassStatements0 extends ClassStatements {

  public ClassStatement classStatement;
  public ClassStatements classStatements;

  public ClassStatements0 (ClassStatement classStatement, ClassStatements classStatements) {
    this.classStatement = classStatement;
    if (classStatement != null) classStatement.setParent(this);
    this.classStatements = classStatements;
    if (classStatements != null) classStatements.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (classStatement != null) classStatement.accept(visitor);
    if (classStatements != null) classStatements.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (classStatement != null) classStatement.traverseTopDown(visitor);
    if (classStatements != null) classStatements.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (classStatement != null) classStatement.traverseBottomUp(visitor);
    if (classStatements != null) classStatements.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ClassStatements0(\n");
      if (classStatement != null)
        buffer.append(classStatement.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (classStatements != null)
        buffer.append(classStatements.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ClassStatements0]");
    return buffer.toString();
  }
}
