/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ClassStatement1 extends ClassStatement {

  public DeclaracaoMetodo declaracaoMetodo;

  public ClassStatement1 (DeclaracaoMetodo declaracaoMetodo) {
    this.declaracaoMetodo = declaracaoMetodo;
    if (declaracaoMetodo != null) declaracaoMetodo.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (declaracaoMetodo != null) declaracaoMetodo.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (declaracaoMetodo != null) declaracaoMetodo.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (declaracaoMetodo != null) declaracaoMetodo.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (declaracaoMetodo != null)
        buffer.append(declaracaoMetodo.toString(" "));
      else
        buffer.append(tab+"  null");
    return buffer.toString();
  }
}
