/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ClassStatement0 extends ClassStatement {

  public Field_var_dec field_var_dec;

  public ClassStatement0 (Field_var_dec field_var_dec) {
    this.field_var_dec = field_var_dec;
    if (field_var_dec != null) field_var_dec.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (field_var_dec != null) field_var_dec.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (field_var_dec != null) field_var_dec.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (field_var_dec != null) field_var_dec.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (field_var_dec != null)
        buffer.append(field_var_dec.toString(" "));
      else
        buffer.append(tab+"  null");
    return buffer.toString();
  }
}
