/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class CodeLiteralStatement implements SyntaxNode {

  private SyntaxNode parent;
  public String lit;

  public CodeLiteralStatement (String lit) {
    this.lit = lit;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    
    buffer.append("  "+tab+lit);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [CodeLiteralStatement]");
    return buffer.toString();
  }
}
