/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class CompilationUnit0 extends CompilationUnit {

  public ClassDeclaration classDeclaration;

  public CompilationUnit0 (ClassDeclaration classDeclaration) {
    this.classDeclaration = classDeclaration;
    if (classDeclaration != null) classDeclaration.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (classDeclaration != null) classDeclaration.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (classDeclaration != null) classDeclaration.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (classDeclaration != null) classDeclaration.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("CompilationUnit0(\n");
      if (classDeclaration != null)
        buffer.append(classDeclaration.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [CompilationUnit0]");
    return buffer.toString();
  }
}
