/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class CompilationUnit1 extends CompilationUnit {

  public ImportList importList;
  public ClassDeclaration classDeclaration;

  public CompilationUnit1 (ImportList importList, ClassDeclaration classDeclaration) {
    this.importList = importList;
    if (importList != null) importList.setParent(this);
    this.classDeclaration = classDeclaration;
    if (classDeclaration != null) classDeclaration.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (importList != null) importList.accept(visitor);
    if (classDeclaration != null) classDeclaration.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (importList != null) importList.traverseTopDown(visitor);
    if (classDeclaration != null) classDeclaration.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (importList != null) importList.traverseBottomUp(visitor);
    if (classDeclaration != null) classDeclaration.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (importList != null)
        buffer.append(importList.toString(tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (classDeclaration != null)
        buffer.append(classDeclaration.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    return buffer.toString();
  }
}
