/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class Expression1 extends Expression {

  public LogicalExpression logicalExpression;

  public Expression1 (LogicalExpression logicalExpression) {
    this.logicalExpression = logicalExpression;
    if (logicalExpression != null) logicalExpression.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (logicalExpression != null) logicalExpression.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (logicalExpression != null) logicalExpression.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (logicalExpression != null) logicalExpression.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Expression1(\n");
      if (logicalExpression != null)
        buffer.append(logicalExpression.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Expression1]");
    return buffer.toString();
  }
}
