/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class Field_var_declarations0 extends Field_var_declarations {

  public Field_var_dec field_var_dec;

  public Field_var_declarations0 (Field_var_dec field_var_dec) {
    this.field_var_dec = field_var_dec;
    if (field_var_dec != null) field_var_dec.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (field_var_dec != null) field_var_dec.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (field_var_dec != null) field_var_dec.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (field_var_dec != null) field_var_dec.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Field_var_declarations0(\n");
      if (field_var_dec != null)
        buffer.append(field_var_dec.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Field_var_declarations0]");
    return buffer.toString();
  }
}
