/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class Form_Par_Seq0 extends Form_Par_Seq {

  public Form_Par form_Par;
  public Form_Par_Seq form_Par_Seq;

  public Form_Par_Seq0 (Form_Par form_Par, Form_Par_Seq form_Par_Seq) {
    this.form_Par = form_Par;
    if (form_Par != null) form_Par.setParent(this);
    this.form_Par_Seq = form_Par_Seq;
    if (form_Par_Seq != null) form_Par_Seq.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (form_Par != null) form_Par.accept(visitor);
    if (form_Par_Seq != null) form_Par_Seq.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (form_Par != null) form_Par.traverseTopDown(visitor);
    if (form_Par_Seq != null) form_Par_Seq.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (form_Par != null) form_Par.traverseBottomUp(visitor);
    if (form_Par_Seq != null) form_Par_Seq.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Form_Par_Seq0(\n");
      if (form_Par != null)
        buffer.append(form_Par.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (form_Par_Seq != null)
        buffer.append(form_Par_Seq.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Form_Par_Seq0]");
    return buffer.toString();
  }
}
