/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class Id_Seq0 extends Id_Seq {

  public String ident;
  public Id_Seq id_Seq;

  public Id_Seq0 (String ident, Id_Seq id_Seq) {
    this.ident = ident;
    this.id_Seq = id_Seq;
    if (id_Seq != null) id_Seq.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (id_Seq != null) id_Seq.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (id_Seq != null) id_Seq.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (id_Seq != null) id_Seq.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Id_Seq0(\n");
    buffer.append("  "+tab+ident);
    buffer.append("\n");
      if (id_Seq != null)
        buffer.append(id_Seq.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Id_Seq0]");
    return buffer.toString();
  }
}
