/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ListParam1 extends ListParam {

  public Parametro parametro;

  public ListParam1 (Parametro parametro) {
    this.parametro = parametro;
    if (parametro != null) parametro.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (parametro != null) parametro.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (parametro != null) parametro.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (parametro != null) parametro.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ListParam1(\n");
      if (parametro != null)
        buffer.append(parametro.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ListParam1]");
    return buffer.toString();
  }
}
