/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class LogicalExpression2 extends LogicalExpression {

  public LogicalExpression logicalExpression;
  public String operador;
  public LogicalExpression logicalExpression2;

  public LogicalExpression2 (LogicalExpression logicalExpression, String operador, LogicalExpression logicalExpression2) {
    this.logicalExpression = logicalExpression;
    if (logicalExpression != null) logicalExpression.setParent(this);
    this.operador = operador;
    this.logicalExpression2 = logicalExpression2;
    if (logicalExpression2 != null) logicalExpression2.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (logicalExpression != null) logicalExpression.accept(visitor);
    if (logicalExpression2 != null) logicalExpression2.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (logicalExpression != null) logicalExpression.traverseTopDown(visitor);
    if (logicalExpression2 != null) logicalExpression2.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (logicalExpression != null) logicalExpression.traverseBottomUp(visitor);
    if (logicalExpression2 != null) logicalExpression2.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LogicalExpression2(\n");
      if (logicalExpression != null)
        buffer.append(logicalExpression.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+operador);
    buffer.append("\n");
      if (logicalExpression2 != null)
        buffer.append(logicalExpression2.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LogicalExpression2]");
    return buffer.toString();
  }
}
