/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class LogicalExpression0 extends LogicalExpression {

  public String nome;

  public LogicalExpression0 (String nome) {
    this.nome = nome;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LogicalExpression0(\n");
    buffer.append("  "+tab+nome);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LogicalExpression0]");
    return buffer.toString();
  }
}
