/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class NumericExpression3 extends NumericExpression {

  public MethodCall methodCall;

  public NumericExpression3 (MethodCall methodCall) {
    this.methodCall = methodCall;
    if (methodCall != null) methodCall.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (methodCall != null) methodCall.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (methodCall != null) methodCall.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (methodCall != null) methodCall.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();    
    if (methodCall != null)
      buffer.append(methodCall.toString("  "+tab));
    return buffer.toString();
  }
}
