/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class NumericExpression0 extends NumericExpression {

  public String nome;
  public NumericExpression numericExpression;

  public NumericExpression0 (String nome, NumericExpression numericExpression) {
    this.nome = nome;
    this.numericExpression = numericExpression;
    if (numericExpression != null) numericExpression.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (numericExpression != null) numericExpression.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (numericExpression != null) numericExpression.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (numericExpression != null) numericExpression.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("NumericExpression0(\n");
    buffer.append("  "+tab+nome);
    buffer.append("\n");
      if (numericExpression != null)
        buffer.append(numericExpression.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [NumericExpression0]");
    return buffer.toString();
  }
}
