/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ParamCallList1 extends ParamCallList {

  public ParamCall paramCall;

  public ParamCallList1 (ParamCall paramCall) {
    this.paramCall = paramCall;
    if (paramCall != null) paramCall.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (paramCall != null) paramCall.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (paramCall != null) paramCall.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (paramCall != null) paramCall.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
      if (paramCall != null)
        buffer.append(paramCall.toString(" "));
    return buffer.toString();
  }
}
