/*
 * Generated by classgen, version 1.5
 * 11/25/13 4:10 PM
 */
package node;

public class Parametro0 extends Parametro {

  public String tipo;
  public String nome;

  public Parametro0 (String tipo, String nome) {
    this.tipo = tipo;
    this.nome = nome;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Parametro0(\n");
    buffer.append("  "+tab+tipo);
    buffer.append("\n");
    buffer.append("  "+tab+nome);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Parametro0]");
    return buffer.toString();
  }
}
