/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ParamCallList0 extends ParamCallList {

  public ParamCall paramCall;
  public String comma;
  public ParamCallList paramCallList;

  public ParamCallList0 (ParamCall paramCall, String comma, ParamCallList paramCallList) {
    this.paramCall = paramCall;
    if (paramCall != null) paramCall.setParent(this);
    this.comma = comma;
    this.paramCallList = paramCallList;
    if (paramCallList != null) paramCallList.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (paramCall != null) paramCall.accept(visitor);
    if (paramCallList != null) paramCallList.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (paramCall != null) paramCall.traverseTopDown(visitor);
    if (paramCallList != null) paramCallList.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (paramCall != null) paramCall.traverseBottomUp(visitor);
    if (paramCallList != null) paramCallList.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ParamCallList0(\n");
      if (paramCall != null)
        buffer.append(paramCall.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+comma);
    buffer.append("\n");
      if (paramCallList != null)
        buffer.append(paramCallList.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ParamCallList0]");
    return buffer.toString();
  }
}
