/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class PrintStatement implements SyntaxNode {

  private SyntaxNode parent;
  public String comando;
  public String lpar;
  public StringExpression stringExpression;
  public String rpar;
  public String ptvirgula;

  public PrintStatement (String comando, String lpar, StringExpression stringExpression, String rpar, String ptvirgula) {
    this.comando = comando;
    this.lpar = lpar;
    this.stringExpression = stringExpression;
    if (stringExpression != null) stringExpression.setParent(this);
    this.rpar = rpar;
    this.ptvirgula = ptvirgula;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (stringExpression != null) stringExpression.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (stringExpression != null) stringExpression.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (stringExpression != null) stringExpression.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(" "+tab+comando);
    buffer.append(" "+lpar);
      if (stringExpression != null)
        buffer.append(stringExpression.toString(" "));
      else
        buffer.append(tab+"  null");
    buffer.append(" "+rpar);
    buffer.append(" "+ptvirgula);
    buffer.append("\n");
    return buffer.toString();
  }
}
