/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class Proc_Dekl_Seq1 extends Proc_Dekl_Seq {


  public Proc_Dekl_Seq1 () {
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Proc_Dekl_Seq1(\n");
    buffer.append(tab);
    buffer.append(") [Proc_Dekl_Seq1]");
    return buffer.toString();
  }
}
