/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class Proc_Dekl_Seq0 extends Proc_Dekl_Seq {

  public Proc_Dekl proc_Dekl;
  public Proc_Dekl_Seq proc_Dekl_Seq;

  public Proc_Dekl_Seq0 (Proc_Dekl proc_Dekl, Proc_Dekl_Seq proc_Dekl_Seq) {
    this.proc_Dekl = proc_Dekl;
    if (proc_Dekl != null) proc_Dekl.setParent(this);
    this.proc_Dekl_Seq = proc_Dekl_Seq;
    if (proc_Dekl_Seq != null) proc_Dekl_Seq.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (proc_Dekl != null) proc_Dekl.accept(visitor);
    if (proc_Dekl_Seq != null) proc_Dekl_Seq.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (proc_Dekl != null) proc_Dekl.traverseTopDown(visitor);
    if (proc_Dekl_Seq != null) proc_Dekl_Seq.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (proc_Dekl != null) proc_Dekl.traverseBottomUp(visitor);
    if (proc_Dekl_Seq != null) proc_Dekl_Seq.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Proc_Dekl_Seq0(\n");
      if (proc_Dekl != null)
        buffer.append(proc_Dekl.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (proc_Dekl_Seq != null)
        buffer.append(proc_Dekl_Seq.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Proc_Dekl_Seq0]");
    return buffer.toString();
  }
}
