/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class ReturnStatement1 extends ReturnStatement {

  public String returnKeyword;
  public StringExpression stringExpression;
  public String ptvirgula;

  public ReturnStatement1 (String returnKeyword, StringExpression stringExpression, String ptvirgula) {
    this.returnKeyword = returnKeyword;
    this.stringExpression = stringExpression;
    if (stringExpression != null) stringExpression.setParent(this);
    this.ptvirgula = ptvirgula;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (stringExpression != null) stringExpression.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (stringExpression != null) stringExpression.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (stringExpression != null) stringExpression.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append("  "+tab+returnKeyword);
      if (stringExpression != null)
        buffer.append(stringExpression.toString("  "));
      else
        buffer.append(tab+"  null");
    buffer.append("  "+ptvirgula);
    return buffer.toString();
  }
}
