/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class Statement7 extends Statement {

  public ReturnStatement returnStatement;

  public Statement7 (ReturnStatement returnStatement) {
    this.returnStatement = returnStatement;
    if (returnStatement != null) returnStatement.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (returnStatement != null) returnStatement.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (returnStatement != null) returnStatement.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (returnStatement != null) returnStatement.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (returnStatement != null)
        buffer.append(returnStatement.toString(" "));
      else
        buffer.append(tab+"  null");
    return buffer.toString();
  }
}
