/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class Statement8 extends Statement {

  public MethodCall methodCall;
  public String ptvirgula;

  public Statement8 (MethodCall methodCall, String ptvirgula) {
    this.methodCall = methodCall;
    if (methodCall != null) methodCall.setParent(this);
    this.ptvirgula = ptvirgula;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (methodCall != null) methodCall.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (methodCall != null) methodCall.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (methodCall != null) methodCall.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (methodCall != null)
        buffer.append(methodCall.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(" "+ptvirgula);
    return buffer.toString();
  }
}
