/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class Statement6 extends Statement {

  public BreakStatement breakStatement;

  public Statement6 (BreakStatement breakStatement) {
    this.breakStatement = breakStatement;
    if (breakStatement != null) breakStatement.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (breakStatement != null) breakStatement.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (breakStatement != null) breakStatement.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (breakStatement != null) breakStatement.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (breakStatement != null)
        buffer.append(breakStatement.toString(" "));
      else
        buffer.append(tab+"  null");
    return buffer.toString();
  }
}
