/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class Statement1 extends Statement {

  public VarDefinition varDefinition;
  public String ptvirgula;

  public Statement1 (VarDefinition varDefinition, String ptvirgula) {
    this.varDefinition = varDefinition;
    if (varDefinition != null) varDefinition.setParent(this);
    this.ptvirgula = ptvirgula;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (varDefinition != null) varDefinition.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (varDefinition != null) varDefinition.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (varDefinition != null) varDefinition.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
      if (varDefinition != null)
        buffer.append(varDefinition.toString(" "));
      else
        buffer.append(tab+"  null");
    buffer.append(" "+ptvirgula);
    buffer.append("\n");
    return buffer.toString();
  }
}
