/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public class StringExpression0 extends StringExpression {

  public StringExpression stringExpression;
  public String mais;
  public StringExpression stringExpression2;

  public StringExpression0 (StringExpression stringExpression, String mais, StringExpression stringExpression2) {
    this.stringExpression = stringExpression;
    if (stringExpression != null) stringExpression.setParent(this);
    this.mais = mais;
    this.stringExpression2 = stringExpression2;
    if (stringExpression2 != null) stringExpression2.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (stringExpression != null) stringExpression.accept(visitor);
    if (stringExpression2 != null) stringExpression2.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (stringExpression != null) stringExpression.traverseTopDown(visitor);
    if (stringExpression2 != null) stringExpression2.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (stringExpression != null) stringExpression.traverseBottomUp(visitor);
    if (stringExpression2 != null) stringExpression2.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    if (stringExpression != null)
      buffer.append(stringExpression.toString(" "));
    else
      buffer.append(tab+"  null");
    buffer.append(" "+mais);
    if (stringExpression2 != null)
      buffer.append(stringExpression2.toString(" "));
    else
      buffer.append(tab+"  null");
    return buffer.toString();
  }
}
