/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */

package node;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
