/*
 * Generated by classgen, version 1.5
 * 11/10/13 6:18 PM
 */
package node;

public class VarAusdr extends Ausdr {

  public Var var;

  public VarAusdr (Var var) {
    this.var = var;
    if (var != null) var.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (var != null) var.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (var != null) var.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (var != null) var.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("VarAusdr(\n");
      if (var != null)
        buffer.append(var.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [VarAusdr]");
    return buffer.toString();
  }
}
