/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */
package node;

public interface Visitor {

  public void visit(Prog prog);
  public void visit(ClassDeclaration classDeclaration);
  public void visit(ImportStatement importStatement);
  public void visit(Field_var_dec field_var_dec);
  public void visit(PrintStatement printStatement);
  public void visit(BreakStatement breakStatement);
  public void visit(MethodCall methodCall);
  public void visit(ParamCall paramCall);
  public void visit(CodeLiteralStatement codeLiteralStatement);
  public void visit(IfStatement ifStatement);
  public void visit(WhileStatement whileStatement);
  public void visit(Parametro parametro);
  public void visit(VarDefinition varDefinition);
  public void visit(CompilationUnit compilationUnit);
  public void visit(CompilationUnit0 compilationUnit0);
  public void visit(CompilationUnit1 compilationUnit1);
  public void visit(ImportList importList);
  public void visit(ImportList0 importList0);
  public void visit(ImportList1 importList1);
  public void visit(Field_var_declarations field_var_declarations);
  public void visit(Field_var_declarations0 field_var_declarations0);
  public void visit(Field_var_declarations1 field_var_declarations1);
  public void visit(Expression expression);
  public void visit(Expression0 expression0);
  public void visit(Expression1 expression1);
  public void visit(NumericExpression numericExpression);
  public void visit(NumericExpression0 numericExpression0);
  public void visit(NumericExpression1 numericExpression1);
  public void visit(NumericExpression2 numericExpression2);
  public void visit(NumericExpression3 numericExpression3);
  public void visit(LogicalExpression logicalExpression);
  public void visit(LogicalExpression0 logicalExpression0);
  public void visit(LogicalExpression1 logicalExpression1);
  public void visit(LogicalExpression2 logicalExpression2);
  public void visit(LogicalExpression3 logicalExpression3);
  public void visit(StringExpression stringExpression);
  public void visit(StringExpression0 stringExpression0);
  public void visit(StringExpression1 stringExpression1);
  public void visit(StringExpression2 stringExpression2);
  public void visit(Statements statements);
  public void visit(Statements0 statements0);
  public void visit(Statements1 statements1);
  public void visit(Statement statement);
  public void visit(Statement0 statement0);
  public void visit(Statement1 statement1);
  public void visit(Statement2 statement2);
  public void visit(Statement3 statement3);
  public void visit(Statement4 statement4);
  public void visit(Statement5 statement5);
  public void visit(Statement6 statement6);
  public void visit(Statement7 statement7);
  public void visit(Statement8 statement8);
  public void visit(ParamCallList paramCallList);
  public void visit(ParamCallList0 paramCallList0);
  public void visit(ParamCallList1 paramCallList1);
  public void visit(ReturnStatement returnStatement);
  public void visit(ReturnStatement0 returnStatement0);
  public void visit(ReturnStatement1 returnStatement1);
  public void visit(ListParam listParam);
  public void visit(ListParam0 listParam0);
  public void visit(ListParam1 listParam1);
  public void visit(IdentList identList);
  public void visit(IdentList0 identList0);
  public void visit(IdentList1 identList1);
  public void visit(DeclaracaoMetodo declaracaoMetodo);
  public void visit(DeclaracaoMetodo0 declaracaoMetodo0);
  public void visit(DeclaracaoMetodo1 declaracaoMetodo1);
  public void visit(ClassStatement classStatement);
  public void visit(ClassStatement0 classStatement0);
  public void visit(ClassStatement1 classStatement1);
  public void visit(ClassStatements classStatements);
  public void visit(ClassStatements0 classStatements0);
  public void visit(ClassStatements1 classStatements1);

}
