/*
 * Generated by classgen, version 1.5
 * 11/26/13 11:02 AM
 */

package node;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
