
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 29 12:52:47 BRST 2013
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 22;
  public static final int LKEY = 9;
  public static final int COMP_OP = 17;
  public static final int BOL_TRUE = 2;
  public static final int UN_OP = 13;
  public static final int LOG_OP = 14;
  public static final int PLUSSIGN = 30;
  public static final int CODE_LITERAL = 31;
  public static final int ASS_OP = 16;
  public static final int DELIM = 11;
  public static final int KEYWORD_CLASS = 24;
  public static final int RPAR = 8;
  public static final int RCOL = 6;
  public static final int TYPE = 19;
  public static final int COMMA = 23;
  public static final int BOL_FALSE = 3;
  public static final int EOF = 0;
  public static final int KEYWORD = 12;
  public static final int RKEY = 10;
  public static final int error = 1;
  public static final int IMPORT_KEYWORD = 32;
  public static final int REAL_NUMBER = 28;
  public static final int QUALIFIED = 21;
  public static final int IDENT = 18;
  public static final int KEYWORD_WHILE = 26;
  public static final int NEG = 4;
  public static final int EXP_OP = 15;
  public static final int ACCESS = 20;
  public static final int RETURN_KEYWORD = 36;
  public static final int STATIC_KEYWORD = 33;
  public static final int INT_NUMBER = 27;
  public static final int KEYWORD_IF = 25;
  public static final int LPAR = 7;
  public static final int LCOL = 5;
  public static final int VECT_TYPE = 34;
  public static final int PRINT = 29;
  public static final int BREAK_KEYWORD = 35;
}

